name: Deploy to EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH Deploy to EC2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
    - name: Deploy via SSH
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        set -e  # Exit on any error
        cd ~/obscurix/backend
        
        # Check if directory exists
        if [ ! -d "~/obscurix/backend" ]; then
          echo "Error: Directory ~/obscurix/backend does not exist"
          exit 1
        fi
        
        # Activate virtual environment
        if [ -f "venv/bin/activate" ]; then
          source venv/bin/activate
        else
          echo "Warning: Virtual environment not found"
        fi
        
        # Pull latest changes
        git pull origin main
        
        # Install/update requirements
        pip install -r requirements.txt
        
        # Restart service
        sudo systemctl restart gunicorn
        
        # Check if service started successfully
        sudo systemctl is-active --quiet gunicorn || {
          echo "Error: Gunicorn failed to start"
          sudo systemctl status gunicorn
          exit 1
        }
        
        echo "Deployment completed successfully"
        EOF
